### PR TITLE
move gates to config file

### PR DESCRIPTION
**Pull request by bicatcho11**
## Description

move gates to config file

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Review by Manason — CHANGES_REQUESTED** [review]
Config should be static. Only the parts of the gates table that are static should exist in config.

**Review by mafewtm — APPROVED** [review]

**Review by BerkieBb — APPROVED** [review]

**Comment by bicatcho11** [comment]
Will new applications be approved?
I will submit new requests
I hope you agree and do not delay

**Comment by BerkieBb** [comment]
> Config should be static. Only the parts of the gates table that are static should exist in config.

This should be addressed yeah.
The `hit` variable is not static so should not exist in the config, move it to a table where the original gates were and name it something like `gatesHit`

**Comment by BerkieBb** [comment]
And fix the conflicts while you're at it

**Comment by Manason** [comment]
Still waiting for previous feedback to be addressed regarding not having dynamic values in the config. Config is immutable (cannot be changed at runtime)

**Comment by BerkieBb** [comment]
@Manason review
@mafewtm review

**Review by BerkieBb — APPROVED** [review]

**Review by mafewtm — APPROVED** [review]

**Pull request closed without merging**
