### PR TITLE
Add a photo when entering the prison

### PR DESCRIPTION
**Pull request by bicatcho11**
## Description

Add a photo when entering the prison

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

### CODE REVIEW

**Review by Fraprwnt — APPROVED** [review]

**Review by Manason — CHANGES_REQUESTED** [review]
Could you take a short video of this and also put it a config value to enable/disable it?

**Comment by Manason** [comment]
> 

This is an image, could you take a video?

**Comment by bicatcho11** [comment]
> > 
> 
> This is an image, could you take a video?
my internet bad upload :(

**Review by Manason — APPROVED** [review]
I'll approve it since it's behind a config, but my suspicion is that the Wait(3000) should be reduced. The total time of this sequence currently is almost 30 seconds.

**Comment by bicatcho11** [comment]
?

**Comment by Manason** [comment]
Resolve conflicts and lint errors

**Review by mafewtm — APPROVED** [review]

**Pull request merged**
